### PR TITLE
Remove Uglifyjs from Webpackplugin.ts

### PR DESCRIPTION
**Pull request by clodal**
#7 
> Since Webpack v4, setting mode to production should already perform UglifyJs optimisations by default (see webpack discussion).

> Including UglifyJsPlugin manually like how we do now, causes side-effects during the compilation, as I have faced in my downstream app and also evident from the stackoverflow question above.

### CODE REVIEW

**Comment by vlasenko** [comment]
@clodal Merged your other PR and now this PR has conflict because of the merge, please resolve the conflict and I will merge this one too

**Comment by clodal** [comment]
@vlasenko thanks, resolved

**Comment by vlasenko** [comment]
@clodal Thank you!

**Comment by clodal** [comment]
@vlasenko Could you publish the new version of spinjs on npm with these changes when you have time please? Thanks!

**Comment by vlasenko** [comment]
@clodal Sure, I will, I'm going to test it now and if everything works I will publish

**Comment by vlasenko** [comment]
@clodal I'm rolling back this PR, because it breaks `spinjs` and seems has no positive changes. You are totally ignoring that `spinjs` has `builder.minify` and `builder.sourceMap` options.

**Comment by vlasenko** [comment]
@clodal This block of code customizes used UglifyJSPlugin options. Obviously you cannot just throw it out and thats it, and what about the work this code did? You should carefully analyze what the code did prior to removing it. 

The option below:
```
optimization: {
  minimize: builder.minify,
```
just turns on UglifyJSPlugin used by Webpack 4 with DEFAULT options, this is the problem. We cannot use default options, we need custom options.

The proper way for Webpack >= 4 to pass custom options as far as I understand is by providing `minimizer` option as well:
https://webpack.js.org/configuration/optimization/#optimization-minimizer

**Comment by clodal** [comment]
@vlasenko Could you explain why do need manual UglifyJS plugin for? Is this to support Webpack versions < 4 only? If so, may I suggest:
```
// src/plugins/WebpackPlugin.ts:44
if (builder.minify && webpackVer < 4) { // <<< Add version check here, since webpack > 4 has built-in minimizer optimization
    ...
    plugins.push(new UglifyJsPlugin(uglifyOpts));
}
```
-- 

> just turns on UglifyJSPlugin used by Webpack 4 with DEFAULT options, this is the problem. We cannot use default options, we need custom options. The proper way for Webpack >= 4 to pass custom options as far as I understand is by providing minimizer option as well:

We can already provide custom options such as `minimizer` by doing so:

```
const config = {
  builders: {
    web: {
      minify: false, // <<< set false to prevent .push(UglifyJSPlugin)
      config: {
        optimization: {
          minimize: true, // <<< set true to override builder.minify and enable Webpack v4 minimize
          minimizer: [
            new TerserPlugin(),
          ],
        },
      },
      ...
    }
  }
}
```

This is made possible because of `spin.merge()` at line 487
```
// src/plugins/WebpackPlugin.ts:485-488
if (stack.hasAny('webpack')) {
  builder.config = builder.config || {};
  builder.config = spin.merge(builder.config, createConfig(builder, spin));
}
```

However, setting builder `minify = false` and `optimization.minimize = true ` still results in overall `optimization.minimize = false` due to the order of the merge. As you can see in the console log below, it still prints false.

```
// console
client: builder config post merge { optimization:
client:    { minimize: false, // <<<< minify = false takes precedence over optimization.minimize = true
client:      minimizer: [ [Object] ],
client:      concatenateModules: false,
client:      ....
```
```
// console.log
if (stack.hasAny('webpack')) {
  builder.config = builder.config || {}; // <<< userConfig defined here
  builder.config = spin.merge(builder.config, createConfig(builder, spin)); // createConfig takes precedence over userConfig
  console.log('builder config post merge', builder.config)
}
```

Moving forward, we could in my opinion (best to worse solutions): 

1) Limit UglifyJSPlugin push to Webpack versions < 4 only, like my first code snippet above (assuming breaks are only happening in < 4)
2) Write a custom function to ensure builder.config.optimization.minimize overrides builder.minify after `spin.merge()`
3) Expose `config.plugins` and allow user to manipulate pop/push into this plugin arrays and return new set of plugins
4) Swap the merge order, but not sure what side effects there will be and whether we should expose core config to be entirely manipulated
5) Open to your suggestions

Thanks for your time!

**Comment by vlasenko** [comment]
@clodal 
> Could you explain why do need manual UglifyJS plugin for?
Because we need to pass options to UglifyJS plugin. For example we need to pass the option to minimize files ending with `.bundle`. The code that you have tried to remove sets this option to UglifyJS plugin - this resulted in bundles for mobile platforms not being minified. If you remove some code you must keep all the features it provided. You have removed the code and you have broken minification of mobile builds. You supposed to test that all the feature the code did are still there - bundles minification, sourceMap generation and not generation depending on the option, the passing `keep_fnames` option to UglifyJS in case of `angular`, you supposed to check all the things that this code did are still there.

**Comment by clodal** [comment]
@vlasenko Okay, thanks for explaining. Thought it was a legacy feature with no side-effects like the LoaderOptionPlugin. In this case 1. of my proposed solutions won't cut it. What do you think about the other solutions? Which do you favour, or do you have a better solution? Thanks!

**Comment by vlasenko** [comment]
@clodal Yes, I have better solution. I have told about it above - in case of Webpack >= 4 set this configured plugin into `optimization.minimizer` property. This way Webpack should use our properly configured UglifyJS plugin and don't use its own instance at the same time

**Comment by clodal** [comment]
@vlasenko Ic, yes that works for me. I was just obsessed about using Webpack's built-in optimizer. Perfect. Thanks very much for your time 👍 Sorry to bother you :)

**Pull request merged**
