### PR TITLE
node debugger is configurable

### PR DESCRIPTION
**Pull request by veeramarni**
We may not need node debugger running all the time, so to make it configurable I have added additional parameter `enableNodeDebugger` to only enable with this parameter. Let me know if this looks good.

### CODE REVIEW

**Comment by vlasenko** [comment]
@veeramarni It looks okay, but please don't add `package-lock.json`

**Comment by veeramarni** [comment]
@vlasenko it's now removed.

**Comment by vlasenko** [comment]
Thank you @veeramarni !

**Comment by vlasenko** [comment]
@veeramarni I had to rollback this Pull Request, because it fails to pass enableNodeDebugger option to `runServer` in all the scenarios

**Pull request merged**
