### PR TITLE
webpack dev server options

### PR DESCRIPTION
**Pull request by verdverm**

### CODE REVIEW

**Comment by vlasenko** [comment]
@verdverm Looks good, but lets add docs as well for the new options into README.md

**Comment by verdverm** [comment]
Added some docs; also removed one line that was a duplicate

**Comment by verdverm** [comment]
@vlasenko I was thinking about that as I wrote it. Cleaned it up, if protocol and port match (for both http(s)), then it will omit it for aesthetics.

**Comment by vlasenko** [comment]
@verdverm Looks good, thank you! Merged it

**Comment by vlasenko** [comment]
@verdverm Published as `spinjs@0.4.161`

**Pull request merged**
